### PR TITLE
[SETUP] l10n_es_aeat_mod347: Add setup

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@pedrobaeza

**Comment by pedrobaeza** [comment]
Why add it here?

**Comment by rousseldenis** [comment]
Because with this, if you merge, it will integrate PR on OCa level

**Comment by pedrobaeza** [comment]
But it's automatically generated once merged, isn't it? I understand that you want to use with pip the PR. I don't really understand the advantages of using pip with all the requirements it has + the twists it makes on addons_path and so on... I really hate this system.

I'll merge this as a favor to your team and you, but you know now my position about all the pip stuff...

**Comment by rousseldenis** [comment]
I know I cannot change you :smile: Thanks !

**Comment by pedrobaeza** [comment]
Yeah, but my position is based on all of these disadvantages, not only by taste. Any way, I am the one that can't change your deployment method through pip, which is a pity.

**Comment by rousseldenis** [comment]
Indeed, we can make (I suppose it was already done) a pros/cons summary. But with pip you install everything with one requirements. It is lightweight, allows to easily install reproductible (and frozen) environments, standard for python, ... that's for pros.

**Comment by pedrobaeza** [comment]
Yeah, that's the only pro I see, but that's only on the ideal world. Then you have to deal with day to day things, having to do things on pre, doing forked branches for merging things, etc. And the rest of the cons are clear:

- Rigidity of the procedures
- Mangling of the addons_path
- Requirement of this setup folder, which is annoying
- Wheels and all of the stuff, which is even more annoying and another point of failure
- not mixable with other methods

and about Python standard, Odoo is not Python, and it's the main problem IMO: try to handle Odoo as a Python library, which is not.

**Pull request merged**
